### ISSUE TITLE
Make a funding proposal for Gardens Swarm

### ISSUE THREAD

**Issue by iviangita** [TECommons/tec-ui#24]
## 📋 Anything to add?

Due to the drop in HNY price, we need to request more funding

Copied and moved from TEC Coordination Workspace [issue 179](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/179) (please check the doc in the comments)

## ⏰ Urgency/Due Date/Blockers?

Blocked slightly by wanting to have the Rehearsal hatch First.

## ❓ Why is it important?

Gotta pay da devs

## 🎉 Subtasks

- [ ] Revise https://forum.1hive.org/t/bootstrapping-the-1hive-gardens-swarm-dao/1159 
- [ ] Post it to the forum
- [ ] 3 days later incorporate feed back and propose it to the 1hive's CV

## 🤼‍ Reviewer

@sembrestels
