### ISSUE TITLE
Hatch improvements

### ISSUE THREAD

**Issue by iviangita** [TECommons/tec-ui#25]
## 📋 Anything to add?

More details can be found on the project board for Garden Swarm here:

https://github.com/orgs/TECommons/projects/1

Copied and moved from TEC Coordination Workspace [issue 111](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/111)

## 🎉 Subtasks
See more at : https://github.com/orgs/TECommons/projects/1

- [ ] Min and max goals 
- [ ] Impact hours conversion
- [ ] Limiting contributions based on CSTK

## 🤼‍ Reviewer

@
